import fs from "node:fs";
import path from "node:path";
import * as p from "@clack/prompts";
import pc from "picocolors";
import { isGitRepo } from "../utils/git.ts";
import { execSync } from "node:child_process";

export async function runHookInstall(): Promise<void> {
  p.intro(pc.cyan("⚓ Git Commit Hook Installer"));

  if (!isGitRepo()) {
    p.cancel(pc.red("Error: Current directory is not a Git repository."));
    return;
  }

  const hooksDir = path.join(process.cwd(), ".git", "hooks");
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // 1. Install prepare-commit-msg (Interactive Conventional Commits assistant)
  const commitHookPath = path.join(hooksDir, "prepare-commit-msg");
  let writeCommitHook = true;

  if (fs.existsSync(commitHookPath)) {
    const overwrite = await p.confirm({
      message: "A 'prepare-commit-msg' hook already exists. Overwrite it to install semantic commits?",
      initialValue: false,
    });
    if (p.isCancel(overwrite)) return;
    writeCommitHook = overwrite;
  }

  if (writeCommitHook) {
    try {
      const hookContent = `#!/bin/sh
# prepare-commit-msg hook generated by ia-tool

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

# Only trigger on interactive commits without pre-defined messages
if [ -z "$COMMIT_SOURCE" ]; then
  # Redirect terminal input back to allow Clack interactive prompts
  exec < /dev/tty
  
  echo "${pc.cyan("⚡ Triggering Conventional Commit Assistant...")}"
  
  if command -v bunx >/dev/null 2>&1; then
    bunx ia-tool commit-all
  elif command -v npx >/dev/null 2>&1; then
    npx ia-tool commit-all
  else
    echo "${pc.red("Error: Bun or Node package runner not found in PATH.")}"
    exit 1
  fi
  
  # Abort the original outer commit since ia-tool completed the commit internally
  exit 1
fi
`;
      fs.writeFileSync(commitHookPath, hookContent, { encoding: "utf-8", mode: 0o755 });
      try { execSync(`chmod +x "${commitHookPath}"`); } catch {}
      p.log.success("Semantic commit hook installed successfully.");
    } catch (err) {
      p.log.error(`Failed to write prepare-commit-msg hook: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // 2. Detect formatting scripts and prompt for pre-commit formatter hook
  let formatScript = "";
  const pkgPath = path.join(process.cwd(), "package.json");
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
      if (pkg.scripts) {
        if (pkg.scripts.format) formatScript = "format";
        else if (pkg.scripts.lint) formatScript = "lint";
      }
    } catch {}
  }

  if (formatScript) {
    const installPreCommit = await p.confirm({
      message: `Detected '${formatScript}' script in package.json. Install a 'pre-commit' hook to automatically format files before commit?`,
      initialValue: true,
    });

    if (p.isCancel(installPreCommit)) return;

    if (installPreCommit) {
      const preCommitPath = path.join(hooksDir, "pre-commit");
      let writePreCommit = true;

      if (fs.existsSync(preCommitPath)) {
        const overwritePC = await p.confirm({
          message: "A 'pre-commit' hook already exists. Overwrite it?",
          initialValue: false,
        });
        if (p.isCancel(overwritePC)) return;
        writePreCommit = overwritePC;
      }

      if (writePreCommit) {
        try {
          const preCommitContent = `#!/bin/sh
# pre-commit hook generated by ia-tool

echo "${pc.cyan("⚡ Running code verification before commit...")}"

if command -v bun >/dev/null 2>&1 && bun run --help | grep -q "run"; then
  bun run ${formatScript}
elif command -v npm >/dev/null 2>&1; then
  npm run ${formatScript}
else
  echo "${pc.red("Error: Package runner not found. Cannot run format script.")}"
  exit 1
fi

if [ $? -ne 0 ]; then
  echo "${pc.red("✖ Verification failed. Aborting commit.")}"
  exit 1
fi

echo "${pc.green("✔ Verification succeeded!")}"
`;
          fs.writeFileSync(preCommitPath, preCommitContent, { encoding: "utf-8", mode: 0o755 });
          try { execSync(`chmod +x "${preCommitPath}"`); } catch {}
          p.log.success("Pre-commit formatting hook installed successfully.");
        } catch (err) {
          p.log.error(`Failed to write pre-commit hook: ${err instanceof Error ? err.message : String(err)}`);
        }
      }
    }
  }

  p.outro(pc.green("✔ Git hooks setup completed."));
}
