import fs from "node:fs";
import path from "node:path";
import * as p from "@clack/prompts";
import pc from "picocolors";
import { isGitRepo } from "../utils/git.ts";
import { execSync } from "node:child_process";

export async function runHookInstall(): Promise<void> {
  p.intro(pc.cyan("⚓ Git Commit Hook Installer"));

  if (!isGitRepo()) {
    p.cancel(pc.red("Error: Current directory is not a Git repository."));
    return;
  }

  const hooksDir = path.join(process.cwd(), ".git", "hooks");
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  const hookPath = path.join(hooksDir, "prepare-commit-msg");
  
  // Check if hook already exists
  if (fs.existsSync(hookPath)) {
    const overwrite = await p.confirm({
      message: "A 'prepare-commit-msg' hook already exists. Overwrite it?",
      initialValue: false,
    });

    if (p.isCancel(overwrite) || !overwrite) {
      p.cancel("Cancelled.");
      return;
    }
  }

  const s = p.spinner();
  s.start("Writing prepare-commit-msg git hook...");

  try {
    const hookContent = `#!/bin/sh
# prepare-commit-msg hook generated by ia-tool

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

# Only trigger on interactive commits without pre-defined messages
if [ -z "$COMMIT_SOURCE" ]; then
  # Redirect terminal input back to allow Clack interactive prompts
  exec < /dev/tty
  
  echo "${pc.cyan("⚡ Triggering Conventional Commit Assistant...")}"
  
  if command -v bunx >/dev/null 2>&1; then
    bunx ia-tool commit-all
  elif command -v npx >/dev/null 2>&1; then
    npx ia-tool commit-all
  else
    echo "${pc.red("Error: Bun or Node package runner not found in PATH.")}"
    exit 1
  fi
  
  # Abort the original outer commit since ia-tool completed the commit internally
  exit 1
fi
`;

    fs.writeFileSync(hookPath, hookContent, { encoding: "utf-8", mode: 0o755 });
    
    // Explicitly chmod +x just in case
    try {
      execSync(`chmod +x "${hookPath}"`);
    } catch {}

    s.stop("Hook written successfully.");
    p.outro(pc.green(`✔ Git hook installed! Standard 'git commit' commands will now run 'ia-tool commit-all' interactively.`));
  } catch (error) {
    s.stop("Failed.");
    p.cancel(error instanceof Error ? error.message : String(error));
  }
}
